README.md
lib/index.js
lib/wrap-request.js

I tested it manually because adding an automated test for it means adding a dev dependency on either `redis` or `ioredis`.
```js
const Bottleneck = require('bottleneck')
const Redis = require('redis')
const client = Redis.createClient({ /* options */ })
const connection = new Bottleneck.RedisConnection({ client })
connection.on('error', err => console.error(err))
const octokit = new Octokit({
throttle: {
onAbuseLimit: (...args) => console.log(...args),
onRateLimit: (...args) => console.log(...args),
Bottleneck, // full, not the light bundle
connection
}
})
await connection.disconnect()
```
It also supports the `ioredis` library:
```js
const Redis = require('ioredis')
const client = new Redis({ /* options */ })
const connection = new Bottleneck.IORedisConnection({ client }) …
```

Clustering support

---

lib/index.js
lib/wrap-request.js
test/integration/index.js

~Not ready for merging.~
What this does is reuse limiters across plugin instantiations as long as their `id` option matches.
`Bottleneck.Group` is a cache for limiter instances, they're automatically deleted after `timeout` ms of inactivity (set to 2 minutes).
Important note: Right now, if the first instance of the plugin uses Redis, then all other instances will use it too even if they don't pass `connection`. And if the first `.plugin()` didn't use redis, then the other `.plugin()` will also not use it.

feat: proof of concept for reused limiters

---

README.md

Thought this minor update to the README could help people starting out with __octokit__ in general. 
`octokit.authenticate()` now gives a deprecation warning and states that the constructor `auth` options is preferred.

Change authenticated method in README

---

test/integration/index.js

Fixes https://github.com/octokit/plugin-throttling.js/issues/51
I ran `watch -n 1 npx nyc mocha test/integration/` for several minutes and didn't see any failures after applying this change. It would fail every 7-8 runs before applying this change.

fix: improve test reliability

---

lib/index.js
lib/wrap-request.js
test/integration/index.js

Fixes #44 
- Allows up to 10 GET/HEAD requests in parallel.
- Throttles the Search API separately.

feat: Throttle search routes, allow parallel GET/HEAD

---

README.md
src/index.ts
test/retry.test.ts

This updates the bottleneck "failed" handler to not retry GraphQL
requests that receive a 401 response. The old behavior was to retry all
GraphQL error responses, which caused the retry to be throttled for an
hour, due to 401 Unauthorized responses including an
`x-ratelimit-remaining` of `0` and a `x-ratelimit-reset` of now + 3600
seconds. The main issue was that the request wasn't being ratelimited,
but the ratelimit headers caused the plugin to wait.
In testing this out, I noticed that GraphQL responses can also receive a
403 Forbidden response when hitting the abuse rate limit. This commit
keeps the functionality for retrying 403 responses for GraphQL requests,
since they signify abuse rate limiting, where 401 responses indicate bad
credentials.
Fixes #229

fix: do not retry GraphQl request in case for 401

---

src/index.ts

addresses part of https://github.com/octokit/octokit.js/issues/2115

fix(typescript): return `{}` instead of `void`

---

src/index.ts
src/wrap-request.ts
test/plugin.test.ts
test/retry.test.ts

fixes octokit/plugin-throttling.js#109

fix: handle full URLs for GraphQL and Search request

---

src/index.ts
test/events.test.ts
test/retry.test.ts

fix: adapt to GitHub's rename of abuse limit to secondary rate limit

---

README.md
src/index.ts
test/events.test.ts
test/plugin.test.ts
test/retry.test.ts

Replace 'abuse limit' with 'secondary limit'

---

src/index.ts

Replace `console.warn` usage with `octokit.log.warn` instead
Open the door to users to hook their own `Octokit` logging system (which uses `console.log` if not defined).
More context here: https://github.com/octokit/plugin-throttling.js/pull/455#issuecomment-1057458294

feat(log): use 'octokit.log.warn' instead of 'console.warn'

---

.github/workflows/test.yml
package-lock.json
package.json
src/index.ts
src/route-matcher.ts
src/types.ts
src/wrap-request.ts
test/events.test.ts
test/plugin.test.ts
test/retry.test.ts
test/typescript-validate.ts

To improve typing for `octokitOptions` for `plugin-throttling`
It can be interesting for:
- deprecating properties/methods 
- auto-complete

Improve types for `ThrottlingOctokitOptions`

---

README.md
src/index.ts
src/types.ts
src/wrap-request.ts
test/retry.test.ts

This is an updated version of #462. 
As asked, replaced `express` in tests with native http module, and fixed the conflicts.
Closes #462
Fixes #442

fix(retry-count): don't leak retryCount between requests: updated

---

src/index.ts

Fixes #555. 
The docs URL for octokit/rest.js has changed since implementation here.

Fix docs link in src/index.ts:86

---

.github/workflows/release.yml
scripts/fix-package-json.js

Resolves #583
----
The released npm package is missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.
With the corrected file patterns, npm will publish all the necessary files again.
This is a mix of an issue with `npm@v9` (https://github.com/npm/cli/issues/6164) and the fact we rely on `pika` for the build step. Pika has been archived [since April 2022](https://github.com/FredKSchott/pika-pack) so there is nothing we can do with Pika.
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API …

fix(build): add script to fix `package.json` from build step

---

src/index.ts
src/types.ts

1. currently `import { throttling } from "@octokit/plugin-throttling";` doesn't lead to loading `@octokit/plugin-throttling/dist-types/types.d.ts` as that's not referenced by the index file anyhow
2. so TS doesn't load that file that contains the `OctokitOptions` augmentation and thus it doesn't see the types for the `OctokitOptions['throttle']` without putting `import "@octokit/plugin-throttling/dist-types/types.d";` at the top of the consuming file

fix(types): move `OctokitOptions` augmentation to the index file

---

src/types.ts

As per the README, it seems that when the `enabled` option is set to `false` no other property is needed, as the plugin is disabled.
Resolves https://github.com/octokit/octokit.js/pull/2448#issuecomment-1550519243

fix(types): don't require any properties if `enabled` is `false`

---

src/index.ts
src/types.ts
test/deprecations.test.ts
test/events.test.ts
test/retry.test.ts

I had a GitHub-internal discussion about this. We cannot give details on how secondary limit rating works as it is meant to avoid API abuse. But for now we came to an agreement that waiting 60s for retries is a good default implementation for handling.
Closes #454, closes #566.

fix: bump minimal retry in case of secondary rate limiting to 60s

---

src/index.ts
test/events.test.ts

Addresses #599, although it won't handle the case where the client and server actually have different times.

fix(retry): Retry requests after the x-ratelimit-reset time, not exactly at it.

---

src/index.ts
test/retry.test.ts

This tries to fix #632, but I haven't tested it.

fix(graphql): GraphQL queries can exceed the rate limit even with x-ratelimit-remaining !== 0.

---

package-lock.json
package.json
src/index.ts
src/types.ts
src/wrap-request.ts
test/exports.test.ts
test/typescript-validate.ts

Fixes #641
This should unblock users, as using `object` doesn't allow users to access options properties in TypeScript.
The types were inferred from the call to `octokit.hook.wrap()`, and also confirmed from the types from`@octokit/core`
https://github.com/octokit/core.js/blob/1c64ce28a2352c88091732985502b257cb242c02/src/types.ts#L55-L59

fix(types): improvements to internal types and `options` parameter

---

package.json
src/index.ts
src/wrap-request.ts
test/events.test.ts
test/exports.test.ts
test/octokit.ts
test/plugin.test.ts
test/retry.test.ts
test/smoke.test.ts
test/tsconfig.test.json

This PR replaces NodeJS internal module imports with `node:` specifier imports.

refactor: use `node:` specifier imports and full relative path imports

---

package-lock.json
package.json
scripts/build.mjs
scripts/update-endpoints/code.js
scripts/update-endpoints/fetch-json.js
src/index.ts
src/wrap-request.ts
test/events.test.ts
test/exports.test.ts
test/octokit.ts
test/plugin.test.ts
test/retry.test.ts
test/smoke.test.ts
test/tsconfig.test.json
test/typescript-validate.ts

BREAKING CHANGE: package is now ESM

feat: package is now ESM

---

src/index.ts

See https://github.com/octokit/plugin-retry.js/issues/519

fix: add missing file extension on bottleneck import

---

scripts/build.mjs

Some tools don't play well with only having the `exports` field present.
See https://github.com/octokit/core.js/pull/662

fix(pkg): add `main` field

---

README.md
scripts/build.mjs

Resolves #694
----
* No "default" defined in package.json -> exports['.']
* "default" field appended to package.json -> exports['.']
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
----
https://github.com/octokit/plugin-retry.js/pull/542
https://github.com/octokit/plugin-paginate-graphql.js/pull/195

Added "default" export in package.json

---

src/index.ts

This was originally 5s:
https://github.com/octokit/plugin-throttling.js/blob/64c537ec3b292afeee63cf1439f95a5894c7b786/src/index.ts#L71
but it was changed in 
https://github.com/octokit/plugin-throttling.js/pull/594

docs(comment): outdated information about the default secondary retry after

---

src/index.ts

we can import Octokit only as type. 
Avoids basically a useless require. 
first merge #720 , then i remove the draft, than it should result in a release.

fix: only import Octokit as type

---

README.md

v17 shipped 4+ years ago, so I think it's safe to remove this warning now.
I realize some folks will still be using v16 and below, but it's a reasonably safe assumption those will be legacy apps that are relatively stable and not under active development.

Remove outdated warning

---

package-lock.json
package.json
src/index.ts
src/types.ts
src/wrap-request.ts
test/octokit.ts
test/plugin.test.ts

Fixes #754 
Fixes octokit/octokit.js#2800
Give auth requests a dedicated queue. This ensures that they don't cause a deadlock when 10+ concurrent requests are made that need authentication (i.e. either we've never authed, or the token has expired).

fix: don't deadlock on 10+ concurrent requests needing auth
